# Generated by Django 5.2.1 on 2025-05-26 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreedor', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('banco', models.CharField(max_length=100)),
                ('firma_recibo', models.CharField(choices=[('APLICA', 'Aplica'), ('NO_APLICA', 'No Aplica')], max_length=20)),
                ('contrato', models.CharField(choices=[('SINDICALIZADO', 'Sindicalizado'), ('CONFIANZA', 'Confianza')], max_length=20)),
                ('escaneado', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=3)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
