# Generated by Django 5.2.1 on 2025-05-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pensionado',
            options={'verbose_name_plural': 'Pensionados'},
        ),
        migrations.AlterField(
            model_name='pensionado',
            name='acreedor',
            field=models.CharField(max_length=100, unique=True, verbose_name='Número de Acreedor'),
        ),
    ]
