# Generated by Django 5.2.1 on 2025-05-26 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pensionados', '0002_alter_pensionado_options_alter_pensionado_acreedor'),
        ('pensionados', '0003_auto_20250525_1829'),
    ]

    operations = [
    ]
