# Generated by Django 5.2.1 on 2025-05-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionados', '0004_merge_20250525_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensionado',
            name='observaciones',
            field=models.TextField(),
        ),
    ]
