# Generated by Django 5.2.1 on 2025-05-26 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionados', '0005_alter_pensionado_observaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RPE', models.CharField(max_length=10, verbose_name='R.P.E')),
                ('nombre', models.CharField(max_length=150)),
                ('cuenta', models.CharField(max_length=20)),
                ('clabe', models.CharField(max_length=18)),
                ('centro', models.CharField(max_length=200)),
                ('banco', models.CharField(max_length=100)),
                ('tipo_pago', models.CharField(choices=[('INTERBANCARIO', 'Interbancario'), ('EFECTIVO', 'Efectivo')], max_length=20)),
                ('contrato', models.CharField(choices=[('ACTIVO', 'Activo'), ('JUBILADO', 'Jubilado')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('SINDICALIZADO', 'Sindicalizado'), ('CONFIANZA', 'Confianza')], max_length=20)),
                ('carta_datos_bancarios_actualizada', models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=10, verbose_name='Carta de Datos Bancarios Actualizada')),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Trabajadores',
            },
        ),
    ]
