# Generated by Django 5.2.1 on 2025-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionados', '0006_trabajador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='RPE',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='centro',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='clabe',
            field=models.CharField(max_length=20),
        ),
    ]
