# Generated by Django 5.2.1 on 2025-05-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pensionados', '0007_alter_trabajador_rpe_alter_trabajador_centro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trabajador',
            options={},
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='RPE',
            field=models.CharField(max_length=10, unique=True, verbose_name='R.P.E'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='carta_datos_bancarios_actualizada',
            field=models.CharField(choices=[('SI', 'Sí'), ('NO', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='centro',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='clabe',
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
